auto: true

markdown: redcarpet
pygments: true
paginate: 8
permalink: /:title

title: isno's blog
url: http://isn0.github.io
feed: /atom.xml
author_info: <a href="http://isn0.github.io/">isno</a>

gems:
    - jekyll-feed